export const RozerpayKeyId = process.env.REACT_APP_ROZERPAY_KEY_ID
export const RozerpayKeySecret = process.env.REACT_APP_ROZERPAY_KEY_SECRECT
export const RozerpaySrcLink = process.env.REACT_APP_ROZERPAY_SRC
export const Apikey = process.env.REACT_APP_API_KEY
export const UserLifetimeSignupApi= process.env.REACT_APP_USERLIFETIMESIGNUP
export const GetMembershipdetailsApi= process.env.REACT_APP_GETMEMBERSHIPDETAILS
export const PlaceUserOrderAndroidApi = process.env.REACT_APP_PLACEUSERORDERANDROID
export const Updateorder = process.env.REACT_APP_UPDATEORDER
export const Updatemembershipplan = process.env.REACT_APP_UPDATEMEMBERSHIPPLAN
export const GOOGLE_PLAY_STORE = process.env.REACT_APP_GOOGLE_PLAY_STORE
export const APPSTORE= process.env.REACT_APP_APPSTORE
